version: '3.5'

#################################################
# Reticulum Node
#
# docker exec -it nexus-broadcast_node01 bash
# docker exec -it nexus-broadcast_node01 rnstatus
# docker exec -it nexus-broadcast_node01 nomadnet
# docker exec -it nexus-broadcast_node01 bash
#
services:
  nexus-prod_nexus:
    container_name: ${NEXUS_CONTAINER}
    image: bsbdock/nexus
    build:
      context: ${NEXUS_COMPOSE_HOME}/bsbdock.nexus_context
      dockerfile: ${NEXUS_DOCKERFILE}
    restart: unless-stopped
    command: rnstatus
    ports:
# Port for the Reticulum Server API for Reticulum Client access if required
#      - 4242:4242  / - 127.0.0.1:4242:4242
      - ${NEXUS_PORT_RNSAPI}:4242
# Port of the NExus Server web client and Mobile App TCP API
#      - 4280:4280 / - 127.0.0.1:4280:4180
#      - 4281:4281 / - 127.0.0.1:4281:4181
      - ${NEXUS_PORT_WEB}:4280
      - ${NEXUS_PORT_JSONAPI}:4281
#    devices:
#      - "/dev/ttyACM0:/dev/ttyACM0"
    networks:
      reticulum-test_net:
        aliases:
          - ${NEXUS_CONTAINER_ALIAS}
    volumes:
      - type: bind
        source: ${NEXUS_COMPOSE_HOME}/${NEXUS_ROOT_BIND}
        target: ${NEXUS_ROOT}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#################################################
# Reticulum Networks
#
networks:
  reticulum-test_net:
    name: ${NEXUS_NETWORK}
    driver: bridge
