version: '3.5'

#################################################
# Reticulum Node
#
# docker exec -it nexus-server_node01 bash
# docker exec -it nexus-server_node01 rnstatus
# docker exec -it nexus-server_node01 nomadnet
#
services:
  nexus-server_node01:
    container_name: ${NEXUS_CONTAINER:-nexus-server_node01}

# If image can not be pulled from docker hub run one of the following commands
# bash ./build-arm-v7.sh for building an arm architecture image (Raspberry)
# bash ./build-amd64.sh for building an amd64 architecture image
    image: ${NEXUS_IMAGE:-bsbdock/nexus}

# Build environment for nexus container (default ARM-V7 Architectur)
# Use NEXUS_DOCKERFILE=./Dockerfile_nexus_linux-amd-64 at .env if you want to build for the AMD64 Architecture
    build:
      context: ${NEXUS_COMPOSE_HOME:-~/nexus}/bsbdock.nexus_context
      dockerfile: ${NEXUS_DOCKERFILE:-./Dockerfile_nexus_linux-arm-v7}

    restart: unless-stopped
    command: ${NEXUS_COMMAND:-/bsb/start.sh}
    ports:
# Port for the reticulum server API for reticulum client access if required
# Can be set to 127.0.0.1:4242:4242 to permit access other than from localhost
      - ${NEXUS_PORT_RNSAPI:-4242}:4242
# Port of the nexus server web admin (not yet served)
      - ${NEXUS_PORT_WEB:-4280}:4280
# Port of the nexus server web client and mobile app JSON TCP/IP API
      - ${NEXUS_PORT_JSONAPI:-4281}:4281
    devices:
# USB Port mapped to container to be used by RNode LoRa interface
      - ${NEXUS_RNODE_DEVICE:-/dev/tty0}:/dev/ttyACM0
    env_file:
      - .env
    networks:
      nexus_server_net:
        aliases:
# Hostname alias of container within the network spanned by docker
          - ${NEXUS_CONTAINER_ALIAS:-nexus-server_node01}
    volumes:
      - type: bind
# Mapping used to externalize config files of reticulum, nomadnet and nexus
        source: ${NEXUS_COMPOSE_HOME:-~/nexus}/${NEXUS_ROOT_BIND:-nexus_root}
        target: ${NEXUS_ROOT:-/root}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#################################################
# Reticulum Container Networks
#
networks:
  nexus_server_net:
# Name of the network to be spawned or connected to by docker
    name: ${NEXUS_NETWORK:-nexus-server_net}
    driver: bridge
