#  _         _         _            _         __
# | |       | |       | |          | |       / /
# | |__  ___| |__   __| | ___   ___| | __   / / __   _____  ___   _ ___
# | '_ \/ __| '_ \ / _` |/ _ \ / __| |/ /  / / '_ \ / _ \ \/ / | | / __|
# | |_) \__ \ |_) | (_| | (_) | (__|   <  / /| | | |  __/>  <| |_| \__ \
# |_ __/|___/_ __/ \__,_|\___/ \___|_|\_\/_/ |_| |_|\___/_/\_\\__,_|___/
#
# Copyright (c) 2022 Stephan Becker / Becker-Systemberatung, MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies
# or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# This software contains and uses Reticulum, NomadNet and LXMF
# Copyright (c) 2016-2022 Mark Qvist / unsigned.io, MIT License
#.........................................................................................
version: '3.5'

# BSB.NexusServer Docker service configuration
services:
  nexus-server_node01:
    container_name: ${NEXUS_CONTAINER:-nexus-server_node01}

# If image can not be pulled from docker hub run one of the following commands
# bash ./build-arm.sh for building an arm architecture image
# bash ./build-arm64.sh for building an arm64 architecture image
# bash ./build.sh for building an amd64 architecture image
    image: ${NEXUS_IMAGE:-bsbdock/nexus:latest}

# Build environment for nexus container (default ARM-V7 Architectur)
# Use NEXUS_DOCKERFILE=./Dockerfile_nexus_linux-amd-64 at .env if you want to build for the AMD64 Architecture
#    build:
#      context: ${NEXUS_COMPOSE_HOME:-~/nexus}/bsbdock.nexus_context
#      dockerfile: ${NEXUS_DOCKERFILE:-./Dockerfile_nexus_dev_linux-arm}

    restart: unless-stopped
    command: [ "${NEXUS_COMMAND:-start_nexus_legacy.sh}" ]
    ports:
# Port for the reticulum server API for reticulum client access if required
# Can be set to 127.0.0.1:4242:4242 to permit access other than from localhost
      - ${NEXUS_PORT_RNSAPI:-4242}:4242
# Port of the nexus server web client
      - ${NEXUS_PORT_WEB:-4280}:4280
# Port of the nexus server web client and mobile app JSON TCP/IP API
      - ${NEXUS_PORT_JSONAPI:-4281}:4281
    devices:
# Sound Device mapped to container to be used by TNC software
      - ${NEXUS_SND_DEVICE:-/dev/snd}:/dev/snd
# USB Port mapped to container to be used by RNode LoRa interface
      - ${NEXUS_RNODE_DEVICE:-/dev/tty0}:/dev/ttyRNODE
# USB Port mapped to container to be used for CAT (PPT)
      - ${NEXUS_CAT_DEVICE:-/dev/tty0}:/dev/ttyCAT
    env_file:
      - .env
    networks:
      nexus-server_net:
        aliases:
# Hostname alias of container within the network spanned by docker
          - ${NEXUS_CONTAINER_ALIAS:-nexus-server_node01}
    volumes:
      # Mapping used to externalize config files of reticulum, nomadnet and nexus
      - type: bind
        source: ${NEXUS_COMPOSE_HOME:-~/nexus}/${NEXUS_ROOT_BIND:-nexus_root/.reticulum}
        target: ${NEXUS_ROOT:-/home/bsb/.reticulum}
      - type: bind
        source: ${NEXUS_COMPOSE_HOME:-~/nexus}/${NEXUS_ROOT_BIND:-nexus_root/.nomadnetwork}
        target: ${NEXUS_ROOT:-/home/bsb/.nomadnetwork}
      - type: bind
        source: ${NEXUS_COMPOSE_HOME:-~/nexus}/${NEXUS_ROOT_BIND:-nexus_root/.nexus}
        target: ${NEXUS_ROOT:-/home/bsb/.nexus}
      - type: bind
        source: ${NEXUS_COMPOSE_HOME:-~/nexus}/${NEXUS_ROOT_BIND:-nexus_root/.direwolf}
        target: ${NEXUS_ROOT:-/home/bsb/.direwolf}
      - type: bind
        source: ${NEXUS_GPIO:-/sys/class/gpio}
        target: /sys/class/gpio
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    labels:
      - "com.centurylinklabs.watchtower.enable=1"

#################################################
# Watchtower automatic update service
  nexus-watchtower:
    profiles:
      - auto-update
    container_name: ${NEXUS_WATCHTOWER:-nexus-watchtower}
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
# Check for updates every 12hrs (60x60x12=43200)
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL:-43200}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      nexus-server_net:

#################################################
# BSB.NexusServer Container Networks
#
networks:
  nexus-server_net:
# Name of the network to be spawned or connected to by docker
    name: ${NEXUS_NETWORK:-nexus-server_net}
    driver: bridge
