#!/bin/bash
#################################################
# Build and tag nexus_server2 container
# bash bsbdock.nexus_context/hooks/post_push

VER=1.4.1
DEV=2.0.0-dev
OS=linux
ARCH1=amd64
ARCH2=arm64
ARCH3=arm

echo ":latest <- $VER"
echo ":dev <- $DEV"
echo "OS=$OS"
echo "Arch1=$ARCH1"
echo "Arch2=$ARCH2"
echo "Arch3=$ARCH3"

echo ""
echo "Remove previous bsbdock/nexus:dev version manifest"
docker manifest rm bsbdock/nexus:dev
echo "Define new dev manifest"
docker manifest create bsbdock/nexus:dev \
  --amend bsbdock/nexus:dev_$OS-$ARCH1 \
  --amend bsbdock/nexus:dev_$OS-$ARCH2 \
  --amend bsbdock/nexus:dev_$OS-$ARCH3
echo "Push new dev multi architecture manifest"
docker manifest push bsbdock/nexus:dev

echo ""
echo "Remove previous bsbdock/nexus:$DEV version manifest"
docker manifest rm bsbdock/nexus:$DEV
echo "Define new $DEV manifest"
docker manifest create bsbdock/nexus:$DEV \
  --amend bsbdock/nexus:"$DEV"_$OS-$ARCH1 \
  --amend bsbdock/nexus:"$DEV"_$OS-$ARCH2 \
  --amend bsbdock/nexus:"$DEV"_$OS-$ARCH3
echo "Push new dev multi architecture manifest"
docker manifest push bsbdock/nexus:"$DEV"

echo ""
echo "Remove previous bsbdock/nexus:$VER version manifest"
docker manifest rm bsbdock/nexus:$VER
echo "Define new $VER manifest"
docker manifest create bsbdock/nexus:$VER \
  --amend bsbdock/nexus:"$VER"_$OS-$ARCH1 \
  --amend bsbdock/nexus:"$VER"_$OS-$ARCH2 \
  --amend bsbdock/nexus:"$VER"_$OS-$ARCH3
echo "Push new $VER multi architecture manifest"
docker manifest push bsbdock/nexus:$VER

echo ""
echo "Remove previous bsbdock/nexus:latest manifest"
docker manifest rm bsbdock/nexus:latest
echo "Define new latest manifest"
docker manifest create bsbdock/nexus:latest \
  --amend bsbdock/nexus:"$VER"_$OS-$ARCH1 \
  --amend bsbdock/nexus:"$VER"_$OS-$ARCH2 \
  --amend bsbdock/nexus:"$VER"_$OS-$ARCH3
echo "Push new latest multi architecture manifest"
docker manifest push bsbdock/nexus:latest

