# Generated by Django 4.0.4 on 2022-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('cluster', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_hash', models.CharField(db_index=True, max_length=22, unique=True)),
                ('private_key', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('last_heard', models.TimeField(auto_now=True)),
                ('announced_role', models.JSONField()),
            ],
        ),
    ]
