############################################################
# bsbdock/reticulum Dockerfile
#
# How to build this container:
# docker build --tag bsbdock/nexus -f Dockerfile_nexus1.3.0_linux-amd64 .
# docker build --tag bsbdock/nexus:1.3.0_linux-amd64 -f Dockerfile_nexus1.3.0_linux-amd64 .
# docker push bsbdock/nexus:1.3.0_linux-amd64
#
# How to invoke a shell into this container:
# docker run -it bsbdock/nexus bash
#
# How to run the reticulum stack as a service
# docker run --rm --name nexus-prod_nexus -it bsbdock/nexus
#
FROM python:3.9

# Set timezone and interactive mode
ENV TZ=Europe/Berlin DEBIAN_FRONTEND=noninteractive

# Update base image if necessary
RUN apt-get update
RUN apt-get install tzdata

# Install pip3
RUN apt -y install python3-pip

# Install Reticulum stack and NomadNet messenger application
RUN pip3 install rns lxmf nomadnet rnodeconf

# Install additional python packages
RUN pip3 install requests

# Install personal helper tools
RUN apt -y install mc nano

# Expose port for Reticulum server TCP Interface (disable as default) 
EXPOSE 4242
# Expose ports for Nexus Server Web and API Interface
EXPOSE 4280
EXPOSE 4281

# Create workdir
RUN mkdir /bsb
RUN mkdir /bsb/nexus_server

# Pull in container start script and make it executable
ARG CACHEBUST=0
COPY start.sh /bsb
RUN chmod ug+x /bsb/start.sh

# Pull in NexusServer
ARG CACHEBUST=0
COPY nexus_server /bsb/nexus_server
RUN chmod ug+x /bsb/nexus_server/nexus_server.py

# Launch Nexus server on start
CMD /bsb/start.sh
