############################################################
# bsbdock/reticulum Dockerfile
#
# How to build this container:
# docker build --tag bsbdock/nexus -f Dockerfile_nexusdev_linux-amd64 .
# docker build --tag bsbdock/nexus:dev_linux-amd64 -f Dockerfile_nexusdev_linux-amd64 .
# docker push bsbdock/nexus:dev_linux-amd64
#
# How to invoke a shell into this container:
# docker run -it bsbdock/nexus bash
#
# How to run the reticulum stack as a service
# docker run --rm --name nexus-prod_nexus -it bsbdock/nexus
#
FROM python:3.9

# Set timezone and interactive mode
ENV TZ=Europe/Berlin DEBIAN_FRONTEND=noninteractive
# set environment variables for python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Update base image if necessary
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install tzdata sudo

# Install pip3
RUN apt -y install python3-pip
RUN pip install --upgrade pip

# Install personal helper tools
RUN apt -y install mc nano vim screen

# Install components for django production deplyment
RUN apt -y install systemctl nginx uwsgi uwsgi-plugin-python3

# Install TNC for radio networking (direwolf)
RUN apt -y install direwolf

# Install personal helper tools
RUN apt -y install mc nano vim screen

# grab gosu for easy step-down from root
RUN set -eux; \
	apt-get update; \
	apt-get install -y gosu; \
	rm -rf /var/lib/apt/lists/*; \
# verify that the binary works
	gosu nobody true

# Set Home dir and path fpr user bsb
ENV HOME /home/bsb
ENV PATH="$HOME/.local/bin:$PATH"

# Add local user 'bsb'
RUN groupadd -r bsb --gid=9001 && useradd -r -g bsb -m --uid=9001 bsb
# Grant him sudo privileges
RUN echo "bsb ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/bsb && \
    chmod 0440 /etc/sudoers.d/bsb

# Copy ressources from context into bsb home
WORKDIR $HOME
COPY . .

# Create folder for static files
WORKDIR $HOME/nexus_django
RUN mkdir static

# Set ownership to usr bsb
RUN chown -R bsb:bsb $HOME

# Switch to user bsb
USER bsb
WORKDIR $HOME

# Install required python packages
RUN pip install --no-cache-dir -r ./requirements.txt

# Collect static files
WORKDIR $HOME/nexus_django
RUN python manage.py collectstatic --no-input --clear

# Back to root
USER root
WORKDIR $HOME

# Make start script executable
RUN chmod ugo+x start.sh
RUN chmod ugo+x start_django.sh

# Configure Nginx
RUN rm /etc/nginx/sites-enabled/default
RUN ln -s /home/bsb/nexus.nginx.conf /etc/nginx/sites-enabled/nexus.nginx.conf
RUN systemctl enable nginx

# Copy entrypoint
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod ug+x /usr/local/bin/entrypoint.sh

# Expose port for Reticulum server TCP Interface (disable as default)
ENV NEXUS_CONTAINER_RNS_PORT 4242
EXPOSE $NEXUS_CONTAINER_RNS_PORT

# Expose port for Nexus Server Web (Nginx)
ENV NEXUS_CONTAINER_WEB_PORT 4280
EXPOSE $NEXUS_CONTAINER_WEB_PORT

# Expose port for Nexus Server API (Gunicorn / Python)
ENV NEXUS_CONTAINER_API_PORT 4281
EXPOSE $NEXUS_CONTAINER_API_PORT

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
# CMD ["/home/bsb/start.sh"]
