############################################################
# bsbdock/reticulum Dockerfile
#
# How to build this container:
# docker build --tag bsbdock/nexus -f Dockerfile_nexus_dev_linux-amd64 .
# docker build --tag bsbdock/nexus:dev_linux-amd64 -f Dockerfile_nexus_dev_linux-amd64 .
# docker run --rm -it bsbdock/nexus:dev_linux-amd64 bash
#
# How to invoke a shell into this container:
# docker run --rm -it bsbdock/nexus:linux_amd64 bash
#
# How to run the reticulum stack as a service
# docker run --rm --name nexus-prod_nexus -it bsbdock/nexus
#
FROM python:3.9

# Set timezone and interactive mode
ENV TZ=Europe/Berlin DEBIAN_FRONTEND=noninteractive
# set environment variables for python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Update base image if necessary
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install tzdata sudo

# Install pip3
RUN apt-get -y install python3-pip

# Build essentials for rust
RUN apt-get -y install build-essential libssl-dev libffi-dev python-dev-is-python3 python2-dev python2
# Install rust
RUN apt-get -y install curl
RUN curl https://sh.rustup.rs -sSf -y1 | sh  -s -- -y --profile minimal --default-toolchain nightly
ENV PATH="/root/.cargo/bin:$PATH"

# Install personal helper tools
RUN apt-get -y install mc nano vim screen

# Install components for django production deplyment
#RUN apt-get -y install systemctl uwsgi uwsgi-plugin-python3 nginx
RUN apt-get -y install nginx systemctl
RUN systemctl enable nginx

# Install TNC for radio networking (direwolf)
RUN apt-get -y install direwolf

# grab gosu for easy step-down from root
RUN set -eux
RUN	apt-get update
RUN	apt-get install -y gosu
RUN	rm -rf /var/lib/apt/lists/*
# verify that the binary works
RUN	gosu nobody true

# Set Home dir and path fpr user bsb
ENV HOME /home/bsb
ENV PATH="$HOME/.local/bin:$PATH"

# Add local user 'bsb'
RUN groupadd -r bsb --gid=9001 && useradd -r -g bsb -m --uid=9001 bsb
# Grant him sudo privileges
RUN echo "bsb ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/bsb && \
    chmod 0440 /etc/sudoers.d/bsb

# Copy ressources from context into bsb home
WORKDIR $HOME
COPY . .

# Configure Nginx
RUN rm /etc/nginx/sites-enabled/default
RUN ln -s /home/bsb/nexus.nginx.conf /etc/nginx/sites-enabled/nexus.nginx.conf

# Make some scripts executable
RUN chmod +x entrypoint.sh
RUN chmod +x start.sh
RUN chmod +x start_django.sh
# RUN chmod +x $HOME/nexus_django/manage.py

# Move script to bin
RUN mv entrypoint.sh /usr/local/bin
RUN mv start.sh /usr/local/bin
RUN mv start_django.sh /usr/local/bin

# Create folder for static files
RUN mkdir $HOME/nexus_django/static

# Set ownership to usr bsb
RUN chown -R bsb:bsb .

# Switch to user bsb
USER bsb
WORKDIR $HOME

# Upgrade pip
RUN pip install --upgrade pip

# Install required python packages
#RUN pip install --no-cache-dir -r ./requirements.txt
RUN pip install -r ./requirements.txt

# Collect static files
WORKDIR $HOME/nexus_django
#RUN python manage.py collectstatic --no-input --clear
RUN ./manage.py collectstatic --no-input --clear
RUN ./manage.py flush --no-input

# Expose port for Reticulum server TCP Interface (disable as default)
ENV NEXUS_CONTAINER_RNS_PORT 4242
EXPOSE $NEXUS_CONTAINER_RNS_PORT

# Expose port for Nexus Server Web (Nginx)
ENV NEXUS_CONTAINER_WEB_PORT 4280
EXPOSE $NEXUS_CONTAINER_WEB_PORT

# Expose port for Nexus Server API (Gunicorn / Python)
ENV NEXUS_CONTAINER_API_PORT 4281
EXPOSE $NEXUS_CONTAINER_API_PORT

ENTRYPOINT ["entrypoint.sh"]
# CMD ["/home/bsb/start.sh"]
